import { useMemo, useState } from 'react'
import { ArrowRight, ExternalLink, Network } from 'lucide-react'
import { buildDiscoveryGraph } from './utils/crawlerUtils'

const nodeColor = { indexable: '#34d399', noindex: '#fbbf24', blocked: '#fb7185', error: '#ef4444', redirect: '#38bdf8', unverified: '#64748b' }
const edgeStyle = { sitemap: { stroke: '#64748b', dash: '' }, 'internal-link': { stroke: '#38bdf8', dash: '' }, redirect: { stroke: '#60a5fa', dash: '5 4' }, canonical: { stroke: '#a78bfa', dash: '2 4' } }

export default function DiscoveryGraph({ crawlerData, activeGraphNode, setActiveGraphNode }) {
  const graph = useMemo(() => buildDiscoveryGraph(crawlerData), [crawlerData])
  const [relations, setRelations] = useState(() => new Set(['sitemap', 'internal-link', 'redirect', 'canonical']))
  const visibleLinks = graph.graphLinks.filter(link => relations.has(link.type))
  const toggle = type => setRelations(current => { const next = new Set(current); if (next.has(type)) next.delete(type); else next.add(type); return next })
  const selected = activeGraphNode && graph.nodeMap.get(activeGraphNode.id)

  return (
    <section className="min-w-0 overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--panel)]" aria-labelledby="discovery-graph-title">
      <header className="flex flex-wrap items-start justify-between gap-3 border-b border-[var(--border)] px-5 py-4"><div><p className="m-0 text-[10px] font-bold uppercase tracking-[.12em] text-[var(--accent)]">Relationship map</p><h2 id="discovery-graph-title" className="mt-1.5 text-sm font-bold uppercase tracking-[.05em] text-[var(--text)]">5. Discovery Graph</h2><p className="mt-1 text-xs text-[var(--muted)]">Actual sitemap, internal-link, redirect, and canonical discovery paths.</p></div>{graph.sampled && <span className="rounded-full border border-amber-400/20 bg-amber-400/10 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.06em] text-amber-300">Sampled graph</span>}</header>
      <div className="flex flex-wrap gap-2 border-b border-[var(--border)] px-4 py-3">{Object.keys(edgeStyle).map(type => <button key={type} type="button" aria-pressed={relations.has(type)} onClick={() => toggle(type)} className={`rounded-full border px-2.5 py-1 text-[9px] capitalize ${relations.has(type) ? 'border-sky-400/30 bg-sky-400/10 text-sky-300' : 'border-[var(--border)] text-[var(--faint)]'}`}>{type.replace('-', ' ')}</button>)}</div>
      <div className="grid min-h-[390px] xl:grid-cols-[minmax(0,1fr)_255px]">
        <div className="min-w-0 overflow-x-auto overflow-y-hidden border-b border-[var(--border)] bg-[#080d14] [contain:layout_paint] xl:border-b-0 xl:border-r">
          {graph.graphNodes.length ? <svg width={graph.canvasWidth} height={graph.canvasHeight} role="img" aria-label="Discovery relationship graph" className="block">
            {visibleLinks.map(link => { const source = graph.nodeMap.get(link.source); const target = graph.nodeMap.get(link.target); if (!source || !target) return null; const dx = target.x - source.x; const style = edgeStyle[link.type]; return <path key={`${link.source}-${link.target}-${link.type}`} d={`M ${source.x} ${source.y} C ${source.x + dx / 2} ${source.y}, ${source.x + dx / 2} ${target.y}, ${target.x} ${target.y}`} fill="none" stroke={style.stroke} strokeWidth="1.2" strokeDasharray={style.dash} opacity={selected && (selected.id === source.id || selected.id === target.id) ? .95 : .38}/> })}
            {graph.graphNodes.map(node => { const color = node.type === 'sitemap' || node.type === 'site' ? '#22d3ee' : nodeColor[node.status] || nodeColor.unverified; const active = selected?.id === node.id; return <g key={node.id} transform={`translate(${node.x}, ${node.y})`} onClick={() => setActiveGraphNode(node)} className="cursor-pointer"><circle r={active ? 8 : 5.5} fill={color} stroke={active ? '#fff' : color} strokeWidth={active ? 2 : 1}/><text x="11" y="4" fill={active ? '#fff' : '#cbd5e1'} fontSize="10" fontWeight={active ? 700 : 500}>{truncate(node.name, 24)}</text></g> })}
          </svg> : <div className="flex h-full min-h-72 flex-col items-center justify-center text-center"><Network size={26} className="text-[var(--faint)]"/><p className="mt-3 text-xs text-[var(--muted)]">No discovery relationships are available yet.</p></div>}
        </div>
        <aside className="p-4"><label htmlFor="graph-node-select" className="text-[9px] font-bold uppercase tracking-[.08em] text-[var(--faint)]">Node evidence</label><select id="graph-node-select" value={selected?.id || ''} onChange={event => setActiveGraphNode(graph.nodeMap.get(event.target.value) || null)} className="mt-2 w-full rounded-md border border-[var(--border)] bg-[var(--bg-darker)] px-2 py-2 text-[9px] text-[var(--text)] outline-none focus:border-sky-400/50"><option value="">Select a node</option>{graph.graphNodes.map(node => <option key={node.id} value={node.id}>{node.name} · {node.status}</option>)}</select>{selected ? <div className="mt-3 animate-[slideDown_180ms_ease-out] motion-reduce:animate-none"><div className="flex items-start justify-between gap-2"><strong className="break-all text-[11px] text-[var(--text)]">{selected.name}</strong><span className="shrink-0 rounded-full border px-2 py-1 text-[8px] font-bold uppercase" style={{ color: nodeColor[selected.status] || '#67e8f9', borderColor: `${nodeColor[selected.status] || '#67e8f9'}55` }}>{selected.status}</span></div><a href={selected.url} target="_blank" rel="noreferrer" className="mt-2 inline-flex max-w-full items-center gap-1 break-all text-[9px] leading-4 text-sky-300">{selected.url}<ExternalLink size={9} className="shrink-0"/></a><dl className="mt-4 space-y-2 text-[9px]"><Detail label="Discovered by" value={selected.source || selected.type}/><Detail label="HTTP status" value={selected.httpStatus || 'Not probed'}/><Detail label="Incoming edges" value={selected.incoming}/><Detail label="Outgoing edges" value={selected.outgoing}/><Detail label="Canonical" value={selected.canonical || 'Not declared'}/></dl></div> : <div className="mt-4 rounded-lg border border-dashed border-[var(--border)] p-4 text-[9px] leading-4 text-[var(--faint)]">Select a node in the graph or use the keyboard-accessible selector to inspect its evidence.</div>}<div className="mt-5 border-t border-[var(--border)] pt-4"><h4 className="text-[9px] font-bold uppercase tracking-[.08em] text-[var(--faint)]">Status colors</h4><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(nodeColor).map(([label, color]) => <span key={label} className="flex items-center gap-1.5 text-[8px] capitalize text-[var(--muted)]"><i className="h-1.5 w-1.5 rounded-full" style={{ background: color }}/>{label}</span>)}</div><p className="mt-4 flex items-center gap-1 text-[8px] leading-4 text-[var(--faint)]">Discovery source <ArrowRight size={9}/> destination</p></div></aside>
      </div>
    </section>
  )
}

function Detail({ label, value }) { return <div className="grid grid-cols-[78px_1fr] gap-2"><dt className="text-[var(--faint)]">{label}</dt><dd className="m-0 break-all text-[var(--muted)]">{value ?? '—'}</dd></div> }
function truncate(value, length) { return value.length > length ? `${value.slice(0, length - 1)}…` : value }
